import Link from "next/link";
/* eslint-disable @next/next/no-img-element */

const steps = [
  ["01", "Start with you", "A single selfie gives the styling decision a person, not just a product page."],
  ["02", "Bring the real pieces", "Upload what you own or capture the garment you are considering while you shop."],
  ["03", "Make the call", "Undertone weighs color, contrast, the moment, and your actual options before showing the strongest try-ons."],
];

function Brand() {
  return <Link href="/" className="font-display text-2xl tracking-[-.06em]">Undertone</Link>;
}

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#f6f4ef] text-[#111827]">
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[760px] bg-[radial-gradient(circle_at_82%_16%,#d9f6ca_0%,transparent_27%),radial-gradient(circle_at_20%_15%,#ded7ff_0%,transparent_30%)] opacity-80" />
    <header className="relative z-10 mx-auto flex max-w-[1480px] items-center justify-between px-5 py-5 lg:px-10 lg:py-7"><Brand /><div className="flex items-center gap-2 sm:gap-4"><Link href="/app" className="hidden rounded-full px-4 py-2.5 text-sm font-semibold text-[#525765] transition hover:bg-white/65 sm:block">Open studio</Link><Link href="/app?demo=1" className="rounded-full bg-[#111827] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-[#111827]/15 transition hover:-translate-y-0.5">See the decision</Link></div></header>

    <section className="relative z-10 mx-auto grid max-w-[1480px] items-center gap-10 px-5 pb-20 pt-12 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:pb-28 lg:pt-20">
      <div className="max-w-2xl"><p className="eyebrow text-[#6a5ed6]">A styling studio for real life</p><h1 className="mt-6 font-display text-[clamp(4rem,8.2vw,8rem)] leading-[.82] tracking-[-.08em]">Does it work<br /><span className="text-[#6a5ed6]">on you?</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#5c6070] lg:text-xl">Undertone helps you decide what to wear before you commit. Bring a piece from your closet or a shopping tab, add the moment, and see the answer in context.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/app" className="rounded-full bg-[#ff6d7d] px-6 py-4 font-semibold text-[#25121a] shadow-[0_14px_30px_rgba(255,109,125,.27)] transition hover:-translate-y-0.5">Build my look</Link><Link href="/app?demo=1" className="rounded-full border border-[#d7d3cb] bg-white/75 px-6 py-4 font-semibold text-[#242938] transition hover:bg-white">Try the live demo</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-[#666b78]"><span>Personal color lens</span><span>Real garment capture</span><span>YouCam try-on</span></div></div>

      <div className="relative min-h-[560px] lg:min-h-[680px]"><div className="absolute left-[2%] top-[11%] h-[78%] w-[47%] overflow-hidden rounded-[2.4rem] border-[10px] border-[#fffdfa] bg-[#d9e1da] shadow-[0_30px_80px_rgba(35,33,79,.18)]"><img src="/showcase/person.jpg" alt="Person at the start of a styling decision" className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#101525]/80 to-transparent p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#caf3a6]">Start with you</p><p className="mt-2 font-display text-3xl leading-none">Your color signature.</p></div></div><div className="absolute right-[1%] top-0 h-[43%] w-[46%] overflow-hidden rounded-[2.2rem] bg-[#ece8e2] shadow-[0_25px_65px_rgba(32,37,59,.14)]"><img src="/showcase/navy-dress.jpg" alt="Navy dress saved to a look board" className="h-full w-full object-cover" /><span className="absolute left-4 top-4 rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#5d50cf]">Real piece · 01</span></div><div className="absolute bottom-[4%] right-[0%] h-[45%] w-[45%] overflow-hidden rounded-[2.2rem] bg-[#d9eee5] shadow-[0_25px_65px_rgba(32,98,83,.14)]"><img src="/showcase/emerald-dress.jpg" alt="Emerald dress saved to a look board" className="h-full w-full object-cover" /><span className="absolute left-4 top-4 rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#31735e]">Real piece · 02</span></div><div className="absolute bottom-[24%] left-[40%] max-w-[230px] rounded-[1.4rem] border border-white/90 bg-[#fffdfa]/95 p-4 shadow-xl backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#6a5ed6]">One clear call</p><p className="mt-2 font-display text-2xl leading-tight">See the decision before you make it.</p><div className="mt-3 flex items-center gap-2 text-xs text-[#666b78]"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#caf3a6] text-[#1d2913]">✓</span>Color, moment, and you.</div></div></div>
    </section>

    <section className="relative z-10 border-y border-[#e2ddd5] bg-[#111827] px-5 py-8 text-white lg:px-10"><div className="mx-auto flex max-w-[1480px] flex-wrap items-center justify-between gap-5"><p className="font-display text-3xl leading-none tracking-[-.035em] sm:text-4xl">A shopping tab shows the garment.<br /><span className="text-[#caf3a6]">Undertone shows the choice.</span></p><p className="max-w-sm text-sm leading-6 text-white/55">Not a generic palette. Not a compliment machine. A personal read on the pieces already in front of you.</p></div></section>

    <section className="relative z-10 mx-auto max-w-[1480px] px-5 py-20 lg:px-10 lg:py-28"><div className="max-w-2xl"><p className="eyebrow text-[#6a5ed6]">Two ways in</p><h2 className="mt-4 font-display text-6xl leading-[.86] tracking-[-.065em]">Your closet and your cart can live in the same decision.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2"><article className="group rounded-[2rem] border border-[#ded9d2] bg-[#fffdfa] p-7 transition hover:-translate-y-1 hover:shadow-2xl hover:shadow-[#3f356f]/[.07] md:p-9"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#efeaff] text-xl text-[#6559d7]">↑</span><span className="text-xs font-bold uppercase tracking-[.16em] text-[#9b969c]">Wardrobe</span></div><h3 className="mt-16 font-display text-5xl leading-[.88]">Choose what you already own.</h3><p className="mt-5 max-w-md text-[15px] leading-7 text-[#6c6f7b]">Upload the dress you keep reaching for, add a second option, and let the profile and moment turn “which one?” into a useful answer.</p><Link href="/app" className="mt-8 inline-flex rounded-full bg-[#111827] px-5 py-3 text-sm font-semibold text-white">Open my board ↗</Link></article><article className="group rounded-[2rem] border border-[#cfe6c5] bg-[#e7f5df] p-7 transition hover:-translate-y-1 hover:shadow-2xl hover:shadow-[#4c7c3c]/[.08] md:p-9"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#111827] text-xl text-[#caf3a6]">U</span><span className="text-xs font-bold uppercase tracking-[.16em] text-[#61735d]">Shopping</span></div><h3 className="mt-16 font-display text-5xl leading-[.88] text-[#22301e]">Keep the product page open.</h3><p className="mt-5 max-w-md text-[15px] leading-7 text-[#5c6d56]">The floating companion lets you crop a garment from the page you are browsing and send it straight into the same styling board.</p><Link href="/app?demo=1" className="mt-8 inline-flex rounded-full bg-[#ff6d7d] px-5 py-3 text-sm font-semibold text-[#2a141b]">See the shopping flow ↗</Link></article></div></section>

    <section className="relative z-10 bg-[#e9e4ff] px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1480px]"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow text-[#6a5ed6]">The decision loop</p><h2 className="mt-4 font-display text-6xl leading-[.84] tracking-[-.07em]">Less guessing.<br />More getting dressed.</h2></div><p className="max-w-xl text-lg leading-8 text-[#656078]">Undertone combines a personal color lens, the real garment, and the reason you are choosing it. The system stays transparent: you can see what shaped the recommendation.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{steps.map(([number, title, body]) => <article key={number} className="rounded-[1.8rem] border border-[#d4cbed] bg-white/60 p-7"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#111827] text-xs font-bold text-[#caf3a6]">{number}</span><h3 className="mt-12 font-display text-3xl leading-none">{title}</h3><p className="mt-4 text-sm leading-6 text-[#6d687c]">{body}</p></article>)}</div></div></section>

    <section className="relative z-10 mx-auto max-w-[1480px] px-5 py-20 lg:px-10 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-[#6a5ed6]">The visual proof</p><h2 className="mt-4 font-display text-6xl leading-[.86] tracking-[-.065em]">A recommendation you can see.</h2></div><p className="max-w-sm text-sm leading-6 text-[#6d707b]">The final answer is not trapped in a paragraph. YouCam makes the strongest directions visible on the person who asked.</p></div><div className="mt-12 grid gap-5 md:grid-cols-[1.15fr_.85fr]"><div className="relative min-h-[560px] overflow-hidden rounded-[2rem] bg-[#28315d]"><img src="/demo/navy-tryon.jpg" alt="Navy virtual try-on result" className="absolute inset-0 h-full w-full object-cover object-[50%_62%]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#101525]/90 to-transparent p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#caf3a6]">Strongest direction</p><p className="mt-2 font-display text-4xl leading-none">Not just navy. The right kind of navy.</p></div></div><div className="grid gap-5"><Link href="/app?demo=1" aria-label="Open the emerald try-on decision" className="group relative min-h-[270px] overflow-hidden rounded-[2rem] bg-[#bfe5db]"><img src="/demo/emerald-tryon.jpg" alt="Emerald virtual try-on result" className="absolute inset-0 h-full w-full object-cover object-[50%_82%] transition duration-500 group-hover:scale-[1.03]" /><div className="absolute right-5 top-5 rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#5d50cf] opacity-0 transition group-hover:opacity-100">Open full read ↗</div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#101525]/80 to-transparent p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.17em] text-white/70">Another direction</p><p className="mt-2 font-display text-3xl leading-none">A different mood, made visible.</p></div></Link><div className="rounded-[2rem] bg-[#111827] p-7 text-white"><p className="eyebrow text-[#cabdff]">Built around your context</p><p className="mt-4 font-display text-3xl leading-tight">Open the evidence when you want it. Keep the decision calm when you don&apos;t.</p><Link href="/app?demo=1" className="mt-6 inline-flex text-sm font-semibold text-[#caf3a6]">Step into the sample decision ↗</Link></div></div></div></section>

    <section className="relative z-10 px-5 pb-12 lg:px-10 lg:pb-16"><div className="mx-auto max-w-[1480px] overflow-hidden rounded-[2.2rem] bg-[#ff6d7d] px-7 py-12 md:px-12 md:py-16"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="eyebrow text-[#7d3040]">Start with one real piece</p><h2 className="mt-4 max-w-3xl font-display text-6xl leading-[.84] tracking-[-.07em] text-[#2a141b]">Your next outfit deserves a better answer.</h2></div><Link href="/app" className="rounded-full bg-[#111827] px-6 py-4 text-sm font-semibold text-white">Open Undertone ↗</Link></div></div></section>
    <footer className="relative z-10 mx-auto flex max-w-[1480px] flex-wrap items-center justify-between gap-4 px-5 pb-8 text-xs text-[#8b8790] lg:px-10"><Brand /><span>Skin-aware apparel decisions · built with YouCam</span></footer>
  </main>;
}
